### PR TITLE
Added initial Dockerfile for 0.12_2.2

### PR DESCRIPTION
**Pull request by seguer**

### CODE REVIEW

**Comment by seguer** [comment]
@tomjowitt @jsok please review

I was able to build and then run locally when testing and got the versions of:
- node
- npm
- ruby
- gem

**Comment by jsok** [comment]
I'd be keen to try `node:5`. I've been using it locally to great success...

**Comment by seguer** [comment]
I can create another version with node 5 but I'd like to get this one working first -- it's already an upgrade on the 0.10 we're using currently (but a "smaller" upgrade).

**Comment by jsok** [comment]
LGTM

**Pull request merged**
